config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :users, only: [:show, :edit, :update], param: :nickname do
    defaults format: :json do
      get :notes_category_ratio
    end
    scope module: :users do
      resources :my_lists, only: [:index]
      resources :notes, only: [:index]
      post '/subscribe_my_lists/:my_list_id', to: "subscribe_my_lists#create", as: :create_subscribe_my_list
      delete '/subscribe_my_lists/:my_list_id', to: "subscribe_my_lists#destroy", as: :destroy_subscribe_my_list
    end
  end

  namespace :information do
    get 'manual'
    get 'policy'
  end

  resources :top, only: [:index]
  resources :notes, only: [:index, :show]
  resources :client_downloads, only: [:index]
  get '/client_downloads/download'
  resources :admin, only: [:index]
  resources :my_lists, only: [:index, :show, :create, :edit, :update, :destroy]
  get '/my_lists/new/:note_id', to: 'my_lists#new', as: :new_my_list

  resources :my_list_notes, only: [:update]
  post '/my_list_notes', to: 'my_list_notes#create', as: :create_my_list_note
  delete '/my_list_notes', to: 'my_list_notes#destroy', as: :destroy_my_list_note

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'users/token', to: 'users#token', as: 'token_user'
        post 'users/auth', to: 'users#auth', as: 'token_auth'

        post 'notes/uploads', to: 'notes#uploads', as: 'upload_notes'
        get 'notes/downloads', to: 'notes#downloads', as: 'download_notes'
        delete 'notes', to: 'notes#destroys', as: 'delete_notes'
        resources :tags, only: :index
        resources :categories, only: :index
        get 'my_lists', to: 'my_lists#index', as: 'my_lists'
      end
    end
  end

  resources :admin, only: [:index]
  namespace :admin do
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root 'top#index'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :note_tags, dependent: :destroy
  has_many :tags, through: :note_tags

  has_many :my_list_notes, dependent: :destroy
  has_many :my_lists, through: :my_list_notes

  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 30000 }
  validates :directory_path, length: { maximum: 255 }

  before_create :add_guid
  before_destroy :move_deleted_note

  ORDER_LIST = { "create_asc" => "created_at", "create_desc" => "created_at DESC", "update_asc" => "updated_at", "update_desc" => "updated_at DESC", "name_asc" => "title", "name_desc" => "title DESC" }.freeze
  RELADED_NOTE_LIMIT = 6

  scope :specified_order, ->(sort_key) { order(sort_key.present? ? Note::ORDER_LIST[sort_key] : Note::ORDER_LIST["update_desc"]) }
  scope :full_search, ->(query) { where('notes.title @@ ? OR notes.body @@ ?', query, query) }
  scope :high_light_full_search, lambda { |query|
    full_search(query)
      .select("*, pgroonga_snippet_html(notes.body, pgroonga_query_extract_keywords('#{query}')) AS high_light_body")
  }
  scope :tags_search, lambda { |tag_params|
    tags = tag_params.split(',')
    tag_ids = Tag.where(name: tags).ids
    return none unless tags.size == tag_ids.size

    note_ids = NoteTag.where(tag_id: tag_ids).group(:note_id).having('count(*) = ?', tag_ids.size).pluck(:note_id)
    where(id: note_ids)
  }

  scope :category_ratio, lambda {
    joins(:category)
      .group("categories.name").order("categories.name").count
  }

  def add_guid
    self.guid = SecureRandom.uuid
  end

  def move_deleted_note
    throw(:abort) unless DeletedNote.note_save(guid, user_id)
  end

  def create_note_tags(tags)
    note_tags.destroy_all
    return [] if tags.blank?

    errors = []
    tags.each do |tag|
      tag_id = tag[:id].present? ? tag[:id] : Tag.find_or_create_by(name: tag[:name]).id
      errors.push(tag) unless note_tags.new(tag_id: tag_id).save
    end
    errors
  end

  def upload_note(word_count, is_create, tags)
    if save
      [{ guid: guid, errors: errors.details, tag_errors: create_note_tags(tags), note_id: id }, { note_id: id, word_count: word_count, is_create: is_create }]
    else
      [{ guid: nil, errors: errors.details, tag_errors: [], note_id: id }, nil]
    end
  end

  class << self
    def upload(user_id, guid, note_params, tags)
      note = find_by(guid: guid, user_id: user_id)
      word_count = note_params[:body].size
      if note
        word_count = (word_count - note.body.size).abs
        is_create = 'false'
        note.attributes = note_params
      else
        is_create = 'true'
        note = new(note_params.merge(user_id: user_id))
      end
      note.upload_note(word_count, is_create, tags)
    end

    def directory_tree
      directory_tree = {}
      pluck(:directory_path).uniq.sort.each do |path|
        create_folders(path, directory_tree)
      end
      directory_tree
    end

    def get_reladed_notes_list(looking_note)
      note_tags = NoteTag.where(tag_id: NoteTag.where(note_id: looking_note.id).pluck(:tag_id))
      if note_tags.blank?
        Note.includes(:user, :category, :tags).where(category_id: looking_note.category_id).where.not(id: looking_note.id).limit(RELADED_NOTE_LIMIT)
      else
        Note.includes(:user, :category, :tags).where("notes.category_id = ? AND notes.id IN (?)", looking_note.category_id, note_tags.pluck(:id)).where.not(id: looking_note.id).limit(RELADED_NOTE_LIMIT)
      end
    end

    def trend_notes(user_id, limit)
      number_read_per_note = ReadNoteLog.new(user_id).number_read_per_note(limit)
      note_ids = number_read_per_note.map { |x| x[:note_id].to_i }
      notes = includes(:user, :category).where(id: note_ids)
      note_ids.collect { |id| notes.detect { |note| note.id == id } }.compact
    end

    private

    def create_folders(directory_path, directory_tree, relative_path = Pathname(''))
      dir_name, child_path = directory_path.split('/', 2)
      return unless dir_name

      relative_path = relative_path.join(dir_name)
      directory_tree[dir_name.to_sym] ||= { path: relative_path.to_path, name: dir_name }
      return unless child_path

      directory_tree[dir_name.to_sym][:children] ||= {}
      create_folders(child_path, directory_tree[dir_name.to_sym][:children], relative_path)
    end
  end
end

app/controllers/admin/notes_controller.rb
module Admin
  class NotesController < ApplicationController
    before_action :authenticate_admin!
    before_action :get_notes, only: :index
    before_action :get_note, only: [:edit, :update, :destroy]

    def new
      @note = Note.new
    end

    def create
      @note = Note.new(note_params)
      if @note.save
        redirect_to admin_notes_path, notice: '作成に成功'
      else
        render :new
      end
    end

    def update
      if @note.update(note_params)
        redirect_to admin_notes_path, notice: '更新に成功'
      else
        render :edit
      end
    end

    def destroy
      @note.destroy!
      redirect_to admin_notes_path, notice: '削除に成功'
    end

    private

    def note_params
      params.require(:note).permit(:title, :body, :category_id, :user_id, :directory_path)
    end

    def get_notes
      @notes = Note.includes(:category, :tags, :user).all
    end

    def get_note
      @note = Note.find(params[:id])
    end
  end
end

app/controllers/api/v1/notes_controller.rb
module Api
  module V1
    class NotesController < ApiBaseController
      protect_from_forgery

      def uploads
        @responses = []
        logs = []
        put_note_params[:notes].each do |note_params|
          response, log = Note.upload(@user.id, note_params[:guid], permit_note_params(note_params), note_params[:tags])
          logs.push(log) if response[:guid]
          @responses.push(response.merge(local_id: note_params[:local_id]))
        end
        StudyLog.new(@user.id).write_study_log(logs)
      end

      def downloads
        @notes = @user.notes.includes(:category, :tags).where('notes.updated_at >= ?', params[:updated_at])
        @deleted_notes = @user.deleted_notes
      end

      def destroys
        @notes = @user.notes.where(guid: (destroy_note_params[:notes].map { |note| note[:guid] })).destroy_all
      end

      private

      def put_note_params
        params.permit(notes: [:local_id, :guid, :title, :body, :category_id, :directory_path, { tags: [:id, :name] }])
      end

      def permit_note_params(note_params)
        note_params.permit(:title, :body, :category_id, :directory_path)
      end

      def destroy_note_params
        params.permit(notes: [:guid])
      end
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include Pagy::Backend   # Pagyを使えるようになる魔法の呪文
  ITEMS_PER_PAGE = 20
  before_action :get_note, only: [:show]
  before_action :get_list, only: [:show]
  before_action :get_reladed_notes_list, only: [:show]
  before_action :write_read_note_log, only: [:show]

  def index
    @notes = Note.includes(:category, :tags, user: { image_attachment: :blob })
    @notes = @notes.where(category_id: params[:category]) if params[:category].present?
    @notes = @notes.high_light_full_search(params[:q]) if params[:q].present?
    @notes = @notes.tags_search(params[:tags]) if params[:tags].present?
    @notes = @notes.specified_order(params[:order])
    @pagy, @notes = pagy(@notes, items: ITEMS_PER_PAGE)
  end

  private

  def get_list
    @my_list_notes = MyListNote.includes(:note).where(my_list_id: params[:my_list_id]).order(:index)
  end

  def get_note
    @note = Note.includes(:user, :category, :tags).find(params[:id])
    get_list if params[:my_list_id].present?
    get_reladed_notes_list
  end

  def get_reladed_notes_list
    @related_notes = Note.get_reladed_notes_list(@note)
  end

  def write_read_note_log
    return if @note.user_id == current_user.id

    ReadNoteLog.new(current_user.id).write_read_note_log([{ note_id: @note.id }])
  end
end

app/controllers/users/notes_controller.rb
module Users
  class NotesController < ApplicationController
    include Pagy::Backend
    ITEMS_PER_PAGE = 20

    def index
      @notes = current_user.notes.includes(:tags, :category, user: { image_attachment: :blob })
      @directory_tree = @notes.directory_tree
      @notes = @notes.where(category_id: params[:category]) if params[:category].present?
      @notes = @notes.where('notes.directory_path LIKE ?', "#{params[:directory_path]}%")
      @notes = @notes.high_light_full_search(params[:q]) if params[:q].present?
      @notes = @notes.tags_search(params[:tags]) if params[:tags].present?
      @notes = @notes.specified_order(params[:order])
      @pagy, @notes = pagy(@notes, items: ITEMS_PER_PAGE, link_extra: 'data-remote="true"')
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  include Pagy::Frontend
end

app/views/notes/_note_index.html.haml
%hr.notes__hr--top
- if notes.present?
  - notes.each do |note|
    .notes__note
      .notes__note-user-image
        - if note.user.image.attached?
          .notes__note-user-image-icon{ style: "background-image: url(#{rails_blob_path(note.user.image)})" }
        - else
          .notes__note-user-image-icon
      = link_to new_my_list_path(note_id: note.id), class: "notes__add-my-list", remote: true do
        = image_pack_tag 'book_icon_plus.png'
      .notes__note-info{ class: "#{'notes__note-no-tags' if note.tags.blank? }"}
        .notes__note-main
          .notes__note-title
            = link_to note.title, note_path(note), class: 'notes__note-link'
        .notes__note-sub
          .notes__note-category
            = note.category.name
          .notes__note-user
            = "#{t('general.by')} #{note.user.nickname}"
          .notes__note-updated-at
            = l note.updated_at, format: :updated_at
        - if note.tags.present?
          .notes__note-tags
            - note.tags.each do |tag|
              .notes__note-tag
                = tag.name
        .notes_note-body
          - if note.try(:high_light_body) && note.high_light_body[0].present?
            = raw note.high_light_body[0]
          - else
            = note.body[0..100]
- else
  .h3.pb-3.ml-2
    = t('empty.note')

app/views/notes/index.html.haml
.row.m-0.p-0
  .left.col-2
    .left__content
      .left__header
        .left__label
          = t '.search_filter'
      .left__form
        = form_with(model: @notes, url: notes_path, local: true) do |f|
          .left__label
            = f.label :category_id, Category.model_name.human
          .left__select
            = f.collection_select :category_id, Category.all, :id, :name, { include_blank: '選択して下さい', selected: params[:category]}, { onchange: "onChange(this.value);", class: 'form-control left__pull-list'}
      .left__form
        .left__label
          = 'タグ'
        .left__tags
          .tag-search
            %form.tag-search__form{ onsubmit: 'addSearchTag(event)' }
              %input.tag-search__input{ type: 'text', wrap: 'soft' }
            .tag-search__tags.overflow-auto#search_tags
      .left__form
        = form_with(model: @notes, url: notes_path, local: true) do |f|
          .left__label
            = f.label :order, t('.order')
          .left__select
            = f.select :order,[[t('.update_desc'), "update_desc"], [t('.update_asc'), "update_asc"], [t('.create_desc'), "create_desc"], [t('.create_asc'), "create_asc"]], {selected: params[:order]},{ onchange: "setSortParams(this.value);", class: 'form-control left__pull-list'}
  .main.col-8.overflow-auto
    .search
      %form.search__container{ onsubmit: 'setSearchParams(event);' }
        %input#search_field{ type: 'text',  value: params[:q], place_holder: 'キーワード検索', class: "search__text-field"}
        %input.search__icon{ type: 'submit', value: "\uF002"}
    .list-header
      .list-header__content--active
        = link_to notes_path, class: "list-header__link" do
          %span.list-header__link-text--active
            = t '.notes'
      .list-header__content
        = link_to my_lists_path, class: "list-header__link" do
          %span.list-header__link-text
            = t '.my_lists'
    .notes#notes
      = render partial: 'note_index', locals: { notes: @notes }

    .d-flex.justify-content-center.mb-2
      != pagy_bootstrap_nav(@pagy)


  .right.col-2
#new_my_list_form

app/views/notes/index.js.erb
document.getElementById('notes').innerHTML = "<%= j(render partial: 'note_index', locals: { notes: @notes }) %>"

app/views/notes/show.html.haml
.row.m-0.p-0
  .note.col-9
    .note__main
      .note__title
        = @note.title
      .note__user-image
        - if @note.user.image.attached?
          .note__user-image-icon{ style: "background-image: url(#{rails_blob_path(@note.user.image)})" }
        - else
          .note__user-image-icon
      .note__info
        .note__info-row-1
          .note__user
            = "#{t('general.by')} #{@note.user.nickname}"
          .note__updated_date
            = l @note.updated_at, format: :updated_at
        .note__info-row-2
          .note__category
            .note__category-name
              = @note.category.name
          = link_to new_my_list_path(note_id: @note.id), class: "note__add-my-list", remote: true do
            = image_pack_tag 'book_icon_plus.png'
        .note__info-row-3
          .note__tags
            - @note.tags.each do |tag|
              .note__tag
                = tag.name
      %hr
      .note__body
        #markdown_raw.note__body-raw
          = @note.body
        #markdown_render
    .note__related-notes
      .note__related-notes-title
        = t ".related_notes_title"
      .note__related-notes-flex
        - @related_notes.each do |note|
          = link_to note_path(note), class: 'note__related-note' do
            .note__related-note-title
              = note.title
            .note__related-note-category
              = note.category.name
            .note__related-note-user
              = note.user.nickname
            .note__related-note-tags
              - note.tags.each do |tag|
                .note__related-note-tag
                  = tag.name
            .note__related-note-body
              = note.body[0..20]

  - if params[:my_list_id].present?
    .note-my-list.col-3
      .note-my-list__main
        .note-my-list__header
          .note-my-list__header-title
            = @my_list_notes[0].my_list.title
          .note-my-list__move-button
            - @my_list_notes.each do |m|
              - if params[:index].to_i > 0 and params[:index].to_i - 1 == m.index
                .note-my-list__header-button.note-my-list__header-prev{href: '', onclick: "changePage(#{m.note_id},#{m.my_list_id},#{m.index})"}
                  = t '.prev'
              - if @my_list_notes.find_by(index: params[:index].to_i + 1).present? and params[:index].to_i + 1 == m.index
                .note-my-list__header-button.note-my-list__header-next{href: '', onclick: "changePage(#{m.note_id},#{m.my_list_id},#{m.index})"}
                  = t '.next'
        .note-my-list__body
          - @my_list_notes.each do |m|
            .note-my-list__note{href: '', onclick: "changePage(#{m.note_id},#{m.my_list_id},#{m.index})", class: "#{m.note_id == @note.id ? 'note-my-list__note--active' : ''}"}
              .note-my-list__note-index
                = m.index + 1
              .note-my-list__note-title
                = m.note.title
#new_my_list_form