config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :users, only: [:show, :edit, :update], param: :nickname do
    defaults format: :json do
      get :notes_category_ratio
    end
    scope module: :users do
      resources :my_lists, only: [:index]
      resources :notes, only: [:index]
      post '/subscribe_my_lists/:my_list_id', to: "subscribe_my_lists#create", as: :create_subscribe_my_list
      delete '/subscribe_my_lists/:my_list_id', to: "subscribe_my_lists#destroy", as: :destroy_subscribe_my_list
    end
  end

  namespace :information do
    get 'manual'
    get 'policy'
  end

  resources :top, only: [:index]
  resources :notes, only: [:index, :show]
  resources :client_downloads, only: [:index]
  get '/client_downloads/download'
  resources :admin, only: [:index]
  resources :my_lists, only: [:index, :show, :create, :edit, :update, :destroy]
  get '/my_lists/new/:note_id', to: 'my_lists#new', as: :new_my_list

  resources :my_list_notes, only: [:update]
  post '/my_list_notes', to: 'my_list_notes#create', as: :create_my_list_note
  delete '/my_list_notes', to: 'my_list_notes#destroy', as: :destroy_my_list_note

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'users/token', to: 'users#token', as: 'token_user'
        post 'users/auth', to: 'users#auth', as: 'token_auth'

        post 'notes/uploads', to: 'notes#uploads', as: 'upload_notes'
        get 'notes/downloads', to: 'notes#downloads', as: 'download_notes'
        delete 'notes', to: 'notes#destroys', as: 'delete_notes'
        resources :tags, only: :index
        resources :categories, only: :index
        get 'my_lists', to: 'my_lists#index', as: 'my_lists'
      end
    end
  end

  resources :admin, only: [:index]
  namespace :admin do
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root 'top#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :note_tags, dependent: :destroy
  has_many :notes, through: :note_tags
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
end

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < ApplicationController
    before_action :authenticate_admin!
    before_action :get_tags, only: :index
    before_action :get_tag, only: [:edit, :update, :destroy]

    def new
      @tag = Tag.new
    end

    def create
      @tag = Tag.new(tag_params)
      if @tag.save
        redirect_to admin_tags_path, notice: t('flash.create')
      else
        render :new
      end
    end

    def update
      if @tag.update(tag_params)
        redirect_to admin_tags_path, notice: t('flash.update')
      else
        render :edit
      end
    end

    def destroy
      if @tag.destroy
        redirect_to admin_tags_path, notice: t('flash.destroy')
      else
        redirect_to admin_tags_path, notice: t('flash.failed_destroy')
      end
    end

    private

    def tag_params
      params.require(:tag).permit(:name)
    end

    def get_tags
      @tags = Tag.all
    end

    def get_tag
      @tag = Tag.find(params[:id])
    end
  end
end

app/controllers/api/v1/tags_controller.rb
module Api
  module V1
    class TagsController < ApiBaseController
      def index
        @tags = Tag.where('updated_at >= ?', params[:updated_at])
      end
    end
  end
end

app/views/admin/tags/edit.html.haml
.single-container
  %h1
    タグ編集

  = form_with(model: @tag, url: admin_tag_path, local: true) do |f|
    - if f.object.errors.any?
      .alert-warning
        %ul
          - f.object.errors.full_messages.each do |message|
            %li
              = message
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.submit nil, class: 'btn btn-success'

app/views/admin/tags/index.html.haml
.single-container
  %h1
    タグ一覧表示

  = link_to '登録', new_admin_tag_path, class: 'btn btn-success mb-3'

  %table.table.text-nowrap
    %thead.thead-light
      %tr
        %th.col-7
          タグ名
        %th.col-5
    %tbody
      - @tags.each do |tag|
        %tr
          %td
            = tag.name
          %td
            = link_to '編集', edit_admin_tag_path(tag.id), class: 'btn btn-outline-dark'
            = link_to '削除', admin_tag_path(tag.id), method: :delete, data: {confirm: '削除しますか？'}, class: 'btn btn-danger'

app/views/admin/tags/new.html.haml
.single-container
  %h1
    タグ登録

  = form_with(model: @tag, url: admin_tags_path, local: true) do |f|
    - if f.object.errors.any?
      .alert-warning
        %ul
          - f.object.errors.full_messages.each do |message|
            %li
              = message
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.submit nil, class: 'btn btn-success'